/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Bean.CrudVendaMB;
import ConexaoBanco.ConexaoMySQL;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Luan
 */
public class CrudVenda extends javax.swing.JInternalFrame {
    private CrudVendaMB bean = new CrudVendaMB();
    JDesktopPane pai = new JDesktopPane();
    
    public CrudVenda() {
        initComponents();
        atualizaTabela();
    }
    public void atualizaTabela(){
        bean.atualizaTabela(jTable1);
    }
    void setPagina(JDesktopPane areaTrabalho, CrudVendaMB bean) {
        pai = areaTrabalho;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnAdicionarItemEstoque = new javax.swing.JButton();
        VisualizarButton = new javax.swing.JButton();
        VisualizarButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Vendas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnAdicionarItemEstoque.setText("Nova Venda");
        BtnAdicionarItemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarItemEstoqueActionPerformed(evt);
            }
        });

        VisualizarButton.setText("Visualizar");
        VisualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarButtonActionPerformed(evt);
            }
        });

        VisualizarButton1.setText("Relatorio de Vendas");
        VisualizarButton1.setActionCommand("Relatório de Vendas");
        VisualizarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VisualizarButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VisualizarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAdicionarItemEstoque)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdicionarItemEstoque)
                    .addComponent(VisualizarButton)
                    .addComponent(VisualizarButton1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdicionarItemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarItemEstoqueActionPerformed
        // TODO add your handling code here:
        FrmVenda frmCadastroVenda = new FrmVenda();
        pai.add(frmCadastroVenda);
        frmCadastroVenda.setPagina(pai, this);
        frmCadastroVenda.setVisible(true);
    }//GEN-LAST:event_BtnAdicionarItemEstoqueActionPerformed

    private void VisualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarButtonActionPerformed
        // TODO add your handling code here:
        
        int row = jTable1.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Selecione Uma Venda", "", WIDTH);
            return;
        } 
        
        Integer id = (Integer) jTable1.getValueAt(row, 0);
        
        FrmVenda frmVenda = new FrmVenda();
        
        pai.add(frmVenda);
        
        frmVenda.alterar(id);
        frmVenda.setTitle("visualização da venda");
        frmVenda.setVisible(true);
    }//GEN-LAST:event_VisualizarButtonActionPerformed

    private void VisualizarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarButton1ActionPerformed
        // TODO add your handling code here:
        ConexaoMySQL con = new ConexaoMySQL();
        Map parametros = new HashMap();
        String relatorio = "relatorios\\Vendas.jasper";
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(relatorio, parametros, con.Conectar());
            JasperViewer view = new JasperViewer(jasperPrint, false);
            
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(CrudVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_VisualizarButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionarItemEstoque;
    private javax.swing.JButton VisualizarButton;
    private javax.swing.JButton VisualizarButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
}
