/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Bean.CrudEstoqueMB;
import DTO.ItemVendaDTO;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan
 */
public final class CrudEstoqueQTD extends javax.swing.JInternalFrame {
    private CrudEstoqueMB bean = new CrudEstoqueMB();
    private int idProduto;
    private String estoqueVenda = "";
    private FrmVenda frmCadastroVenda = new FrmVenda();
    
    JDesktopPane pai = new JDesktopPane();
    
    public CrudEstoqueQTD(int id_Produto, String estoqueVenda) {
        initComponents();
        this.idProduto = id_Produto;
        this.estoqueVenda = estoqueVenda;
        atualizaTabela(this.idProduto);
        
        if(this.estoqueVenda.equals("E")){
            this.BtnAdicionar.setText("Adicionar");
        }else{
            this.BtnAdicionar.setText("Selecione a QTD");
        }
    }
    
    void passaClass(FrmVenda frmCadastroVenda) {
        this.frmCadastroVenda = frmCadastroVenda;
    }
    
    void setPagina(JDesktopPane areaTrabalho) {
        pai = areaTrabalho;
    }
    
    public void atualizaTabela(int idProduto){
        bean.atualizaTabelaQTD(jTable1, idProduto);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnAdicionar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Estoque");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnAdicionar.setText("Adicionar");
        BtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnAdicionar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAdicionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Selecione Um Item", "", WIDTH);
            return;
        }
        
        Integer idTamanho = (Integer) jTable1.getValueAt(row, 0);
        
        
        FrmCadastroAddQTDEstoque frmCadastroAddQTDEstoque = new FrmCadastroAddQTDEstoque(idProduto, idTamanho, this, estoqueVenda);
        
        pai.add(frmCadastroAddQTDEstoque);
        frmCadastroAddQTDEstoque.passaClass(frmCadastroVenda);
        frmCadastroAddQTDEstoque.setVisible(true);
    }//GEN-LAST:event_BtnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    

}
