/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Bean.CrudEstoqueMB;
import Bean.CrudProdutoMB;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan
 */
//-----
public class CrudEstoque extends javax.swing.JInternalFrame {
    private CrudProdutoMB bean = new CrudProdutoMB();
    private String estoqueVenda = "";
    private FrmVenda frmCadastroVenda = new FrmVenda();
    JDesktopPane pai = new JDesktopPane();
    
    public CrudEstoque() {
        initComponents();
        
        atualizaTabela();
    }
    
    void passaClass(FrmVenda frmCadastroVenda) {
        this.frmCadastroVenda = frmCadastroVenda;
    }
    
    public void atualizaTabela(){
        bean.atualizaTabela(jTable1);
    }
    
    void setPagina(JDesktopPane areaTrabalho, CrudEstoqueMB bean, String estoqueVenda) {
        pai = areaTrabalho;
        this.estoqueVenda = estoqueVenda;
        
        if(estoqueVenda.equals("E")){
            this.BtnAdicionarItemEstoque.setText("Selecione o Produto");
        }else{
            this.BtnAdicionarItemEstoque.setText("Selecione o Produto");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnAdicionarItemEstoque = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Itens Estoque");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtnAdicionarItemEstoque.setText("+");
        BtnAdicionarItemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarItemEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnAdicionarItemEstoque)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAdicionarItemEstoque)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdicionarItemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarItemEstoqueActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Selecione Uma Produto", "", WIDTH);
            return;
        }
        
        Integer id = (Integer) jTable1.getValueAt(row, 0);
        
        CrudEstoqueQTD crudEstoqueQTD = new CrudEstoqueQTD(id, estoqueVenda);
        //frmCadastro.setPagina(this, bean);
        
        pai.add(crudEstoqueQTD);
        
        crudEstoqueQTD.passaClass(this.frmCadastroVenda);
        crudEstoqueQTD.setPagina(pai);
        crudEstoqueQTD.setVisible(true);
    }//GEN-LAST:event_BtnAdicionarItemEstoqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionarItemEstoque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    

}
