/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Bean.CrudProdutoMB;
import DTO.ProdutoDTO;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan
 */
public class FrmCadastroProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCadastroPessoa
     */
    private CrudProdutoMB bean = new CrudProdutoMB();
    private CrudProduto crudProduto = new CrudProduto();
    
    private Integer idProduto;
    
    public FrmCadastroProduto() {
        initComponents();
        
        bean.CarregaComboBoxGrade(GradeComboBox);
    }
    
    void setPagina(CrudProduto formPai) {
        crudProduto = formPai;
    }
    
    void alterar(int id) {
        ProdutoDTO p = new ProdutoDTO();
        idProduto = id;
        p = bean.getById(idProduto);
        
        this.NomeProdutoTextField.setText(p.getNome());
        this.DescricaoProdutoTextField.setText(p.getDescricao());
        
        this.GradeComboBox.setSelectedItem(bean.getNameById(p.getIdGrade()));
        this.GradeComboBox.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        NomeProdutoTextField = new javax.swing.JTextField();
        BtnGravar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DescricaoProdutoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        GradeComboBox = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);

        jLabel6.setText("Nome do Produto:");

        NomeProdutoTextField.setColumns(15);

        BtnGravar.setText("Gravar");
        BtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGravarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição do Produto:");

        jLabel2.setText("Selecione a Grade:");

        GradeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                GradeComboBoxItemStateChanged(evt);
            }
        });
        GradeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NomeProdutoTextField)
                            .addComponent(DescricaoProdutoTextField)
                            .addComponent(GradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGravar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NomeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DescricaoProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGravar)
                    .addComponent(BtnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGravarActionPerformed
        // TODO add your handling code here:
        if(GradeComboBox.getSelectedItem().toString().equals("Selec. Grade")){
            JOptionPane.showMessageDialog(this, "Selecione a Grade!", "", WIDTH);
            return;
        }
        
        if(idProduto == null){
            ProdutoDTO p = new ProdutoDTO();
            
            p.setNome(this.NomeProdutoTextField.getText());
            p.setDescricao(this.DescricaoProdutoTextField.getText());
            p.setIdGrade(bean.getIdByName(this.GradeComboBox.getSelectedItem().toString()));
            
            if(bean.insert(p) != -1){
                JOptionPane.showMessageDialog(this, "Produto inserido com sucesso!", "", WIDTH);
                this.setVisible(false);
                crudProduto.atualizaTabela();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao inserir a Produto!", "", WIDTH);
            }
        }else{
            ProdutoDTO p = new ProdutoDTO();
            
            p.setIdProduto(idProduto);
            p.setNome(this.NomeProdutoTextField.getText());
            p.setDescricao(this.DescricaoProdutoTextField.getText());
            
            if(bean.update(p) != -1){
                JOptionPane.showMessageDialog(this, "Produto alterada com sucesso!", "", WIDTH);
                this.setVisible(false);
                crudProduto.atualizaTabela();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao alterar a Produto!", "", WIDTH);
            }
        }
    }//GEN-LAST:event_BtnGravarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void GradeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_GradeComboBoxItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_GradeComboBoxItemStateChanged

    private void GradeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnGravar;
    private javax.swing.JTextField DescricaoProdutoTextField;
    private javax.swing.JComboBox GradeComboBox;
    private javax.swing.JTextField NomeProdutoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
