/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Bean.CrudEstoqueMB;
import Bean.CrudGradeMB;
import Bean.CrudProdutoMB;
import Bean.CrudVendaMB;
import Bean.LoginMB;
import Bean.PessoaBean;
import javax.swing.JFrame;

/**
 *
 * @author Luan
 */
public class Principal extends JFrame {
    private LoginMB controle = new LoginMB();
    /**
     * Creates new form FrmPrincipal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Golden Semijoias");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastroPessoajMenuItem = new javax.swing.JMenuItem();
        cadastroGradejMenuItem = new javax.swing.JMenuItem();
        cadastroProdutojMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        estoquejMenuItem = new javax.swing.JMenuItem();
        vendasjMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        jMenuBar1.setToolTipText("");

        jMenu1.setText("Cadastro");

        cadastroPessoajMenuItem.setText("Cadastro de Pessoa");
        cadastroPessoajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPessoajMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cadastroPessoajMenuItem);

        cadastroGradejMenuItem.setText("Cadastro de Grade");
        cadastroGradejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroGradejMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cadastroGradejMenuItem);

        cadastroProdutojMenuItem.setText("Cadastro de Produto");
        cadastroProdutojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroProdutojMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(cadastroProdutojMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Financeiro");

        estoquejMenuItem.setText("Estoque");
        estoquejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoquejMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(estoquejMenuItem);

        vendasjMenuItem1.setText("Vendas");
        vendasjMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasjMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(vendasjMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroPessoajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPessoajMenuItemActionPerformed
        // TODO add your handling code here:
        CrudPessoa frmPessoa = new CrudPessoa();
        PessoaBean bean = new PessoaBean();
        areaTrabalho.add(frmPessoa);
        frmPessoa.setPagina(areaTrabalho, bean);
        frmPessoa.show();
    }//GEN-LAST:event_cadastroPessoajMenuItemActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void cadastroGradejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroGradejMenuItemActionPerformed
        // TODO add your handling code here:
        CrudGrade frmGrade = new CrudGrade();
        CrudGradeMB bean = new CrudGradeMB();
        areaTrabalho.add(frmGrade);
        frmGrade.setPagina(areaTrabalho, bean);
        frmGrade.show();
    }//GEN-LAST:event_cadastroGradejMenuItemActionPerformed

    private void cadastroProdutojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProdutojMenuItemActionPerformed
        // TODO add your handling code here:
        CrudProduto crudProduto = new CrudProduto();
        CrudProdutoMB bean = new CrudProdutoMB();
        areaTrabalho.add(crudProduto);
        crudProduto.setPagina(areaTrabalho, bean);
        crudProduto.show();
    }//GEN-LAST:event_cadastroProdutojMenuItemActionPerformed

    private void vendasjMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasjMenuItem1ActionPerformed
        // TODO add your handling code here:
        CrudVenda crudVenda = new CrudVenda();
        CrudVendaMB bean = new CrudVendaMB();
        areaTrabalho.add(crudVenda);
        crudVenda.setPagina(areaTrabalho, bean);
        crudVenda.show();
    }//GEN-LAST:event_vendasjMenuItem1ActionPerformed

    private void estoquejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoquejMenuItemActionPerformed
        // TODO add your handling code here:
        CrudEstoque crudEstoque = new CrudEstoque();
        CrudEstoqueMB bean = new CrudEstoqueMB();
        areaTrabalho.add(crudEstoque);
        crudEstoque.setPagina(areaTrabalho, bean, "E");
        crudEstoque.show();
    }//GEN-LAST:event_estoquejMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Principal principal = new Principal();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
            
            Login login = new Login(principal,true);
            login.setLocationRelativeTo(principal);
            login.setPai(principal);
            login.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenuItem cadastroGradejMenuItem;
    private javax.swing.JMenuItem cadastroPessoajMenuItem;
    private javax.swing.JMenuItem cadastroProdutojMenuItem;
    private javax.swing.JMenuItem estoquejMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem vendasjMenuItem1;
    // End of variables declaration//GEN-END:variables
}
